### ISSUE TITLE
witness node core dump

### ISSUE THREAD

**Issue by jcalfee** [cryptonomex/graphene#221]
This is from the witness node screen on https://graphene.bitshares.org :

```
597036ms th_a       application.cpp:414           get_item             ] Request for item {"item_type":1001,"item_hash":"0005663eae248dc997c358160274c516b89a361e"}
597036ms th_a       application.cpp:422           get_item             ] Serving up block #353854
598013ms th_a       application.cpp:319           handle_block         ] Got block #353855 from network
599013ms th_a       application.cpp:319           handle_block         ] Got block #353856 from network
600026ms th_a       application.cpp:319           handle_block         ] Got block #353857 from network
600166ms th_a       api.cpp:51                    ~database_api        ] freeing database api 78754360
600166ms th_a       api.cpp:56                    ~database_api        ] waiting..
pure virtual method called
terminate called without an active exception

Program received signal SIGABRT, Aborted.
0x00007ffff6c01cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56      ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff6c01cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff6c050d8 in __GI_abort () at abort.c:89
#2  0x00007ffff750c535 in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff750a6d6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff750a703 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff750b1bf in __cxa_pure_virtual () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x0000000001e8379d in fc::detail::callback_functor<void (fc::variant const&)>::operator()(fc::variant const&) const ()
#7  0x0000000001e708e8 in std::_Function_handler<void (fc::variant const&), fc::detail::callback_functor<void (fc::variant const&)> >::_M_invoke(std::_Any_data const&, fc::variant const&) ()
#8  0x0000000001f762a7 in std::function<void (fc::variant const&)>::operator()(fc::variant const&) const ()
#9  0x0000000001f60903 in graphene::app::database_api::on_objects_changed(std::vector<graphene::db::object_id_type, std::allocator<graphene::db::object_id_type> > const&)::{lambda()#1}::operator()() const ()
#10 0x0000000001f6aad4 in fc::detail::void_functor_run<graphene::app::database_api::on_objects_changed(std::vector<graphene::db::object_id_type, std::allocator<graphene::db::object_id_type> > const&)::{lambda()#1}>::run(void*, fc::detail::void_functor_run<graphene::app::database_api::on_objects_changed(std::vector<graphene::db::object_id_type, std::allocator<graphene::db::object_id_type> > const&)::{lambda()#1}>) ()
#11 0x0000000002424909 in fc::task_base::run_impl() ()
#12 0x000000000242489a in fc::task_base::run() ()
#13 0x00000000024192ba in fc::thread_d::run_next_task() ()
#14 0x000000000241975e in fc::thread_d::process_tasks() ()
#15 0x0000000002418dd1 in fc::thread_d::start_process_tasks(long) ()
#16 0x0000000002775681 in make_fcontext ()
#17 0x0000000000000000 in ?? ()
(gdb) 
```

**Comment by jcalfee** [comment]
Happened after running for about 24 hours.

**Comment by theoreticalbts** [comment]
Maybe fixed by https://github.com/cryptonomex/fc/commit/3cd9ed43861dc64a6b8841d9663a94c1bde259ec

**Comment by theoreticalbts** [comment]
If it hasn't popped up since August, it's probably fixed.
