### ISSUE TITLE
Program received signal SIGABRT, Aborted.

### ISSUE THREAD

**Issue by abitmore** [cryptonomex/graphene#270]
```
1703036ms th_a       application.cpp:492           get_blockchain_synop ] reference_point: 00050fe67a7e2215e10fd75b33016d76e568b1fd nu
mber_of_blocks_after_reference_point: 9995 result: ["00010fe68b5c9d3c47cd5d510c22f579839f195e","00030fe69ce24247979807441e4d54551dc3c4
7f","00040fe6ec7956b8105c2cd31b548cc61c245c5c","00048fe632ec74d71723eabf662af4e9a59103d5","0004cfe61da9189b6bd8f7b263dc0fb1e80185e3","
0004efe69f6defb942652e20b039fb58a3d3d48e","0004ffe6c2522f93b60bcbb2a1cd9125b70f187a","000507e6a190f71ecd694d5dbd65ccdbfd0842eb","00050
be6ecc5fe4980252fdd581722cd77b31370","00050de6c211bb1b2109cfdd8ce31d4eb05e535f","00050ee6fcbd0c59537b0f787bf1b9ebca921c81","00050f6693
cd42b34dfcc1de5a3f94feb0e43b92","00050fa6e0d1dde6a99cc1ab909bd550065ed462","00050fc67278aca6be23f7dda30ef9d0c229ba1a","00050fd670ba0fb
99326d4e4fa3de1a30d627575","00050fde357dd87b7beb148e06828fa608efa275","00050fe28561b9f2b446665a8e51b3060c008942","00050fe4cb8a81be64de
a681766bc776b19ef239","00050fe5755559090fada1239e1210e89951bd5f","00050fe67a7e2215e10fd75b33016d76e568b1fd"]
1705190ms th_a       application.cpp:370           handle_block         ] Error when pushing block:
10 assert_exception: Assert Exception
item->num > std::max<int64_t>( 0, int64_t(_head->num) - (_max_size) ): attempting to push a block that is too old
    {"item->num":331751,"head":334568,"max_size":11}
    th_a  fork_database.cpp:69 _push_block

    {"new_block":{"previous":"00050fe67a7e2215e10fd75b33016d76e568b1fd","timestamp":"2015-08-25T00:48:13","witness":"1.6.75","next_secret_hash":"c976d8d9c7b714ac8fbe4aa4e0dccdadc70a42a0","previous_secret":"cef354552b0afc6faeab2a583d81d11094b4ac28","transaction_merkle_root":"0000000000000000000000000000000000000000","extensions":[],"witness_signature":"1f37d175450a43aa3c00ce1b16dc398b3776cf19a19e4b54e41764ab0bdeefdb4117a01237689803911c50877b00486075d5a80a383213a267cfa4a69d894a35b5","transactions":[]}}
    th_a  db_block.cpp:176 _push_block
witness_node: /app/bts/graphene-test1.1/libraries/net/node.cpp:1511: void graphene::net::detail::node_impl::schedule_peer_for_deletion(const peer_connection_ptr&): Assertion `_closing_connections.find(peer_to_delete) == _closing_connections.end()' failed.

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffff4d16700 (LWP 566)]
0x00007ffff6c01cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56      ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) where
#0  0x00007ffff6c01cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff6c050d8 in __GI_abort () at abort.c:89
#2  0x00007ffff6bfab86 in __assert_fail_base (fmt=0x7ffff6d4b830 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n",
    assertion=assertion@entry=0x2a76de0 "_closing_connections.find(peer_to_delete) == _closing_connections.end()",
    file=file@entry=0x2a75d08 "/app/bts/graphene-test1.1/libraries/net/node.cpp", line=line@entry=1511,
    function=function@entry=0x2a7e4a0 <graphene::net::detail::node_impl::schedule_peer_for_deletion(std::shared_ptr<graphene::net::peer_connection> const&)::__PRETTY_FUNCTION__> "void graphene::net::detail::node_impl::schedule_peer_for_deletion(const peer_connection_ptr&)") at assert.c:92
#3  0x00007ffff6bfac32 in __GI___assert_fail (
    assertion=0x2a76de0 "_closing_connections.find(peer_to_delete) == _closing_connections.end()",
    file=0x2a75d08 "/app/bts/graphene-test1.1/libraries/net/node.cpp", line=1511,
    function=0x2a7e4a0 <graphene::net::detail::node_impl::schedule_peer_for_deletion(std::shared_ptr<graphene::net::peer_connection> const&)::__PRETTY_FUNCTION__> "void graphene::net::detail::node_impl::schedule_peer_for_deletion(const peer_connection_ptr&)")
    at assert.c:101
#4  0x00000000026dfe6b in graphene::net::detail::node_impl::schedule_peer_for_deletion (this=0xa611700, peer_to_delete=...)
    at /app/bts/graphene-test1.1/libraries/net/node.cpp:1511
#5  0x00000000026f55ec in graphene::net::detail::node_impl::on_connection_closed (this=0xa611700, originating_peer=0x7fffe03db380)
    at /app/bts/graphene-test1.1/libraries/net/node.cpp:2772
#6  0x00000000027d3db0 in graphene::net::peer_connection::on_connection_closed (this=0x7fffe03db380,
    originating_connection=0x7fffe03db3b0) at /app/bts/graphene-test1.1/libraries/net/peer_connection.cpp:270
#7  0x00000000027dc4cf in graphene::net::detail::message_oriented_connection_impl::read_loop (this=0x7fffe03e1330)
    at /app/bts/graphene-test1.1/libraries/net/message_oriented_connection.cpp:217
#8  0x00000000027dbdaf in graphene::net::detail::message_oriented_connection_impl::__lambda0::operator() (__closure=0x7fffe01028d8)
    at /app/bts/graphene-test1.1/libraries/net/message_oriented_connection.cpp:117
#9  0x00000000027e1048 in fc::detail::void_functor_run<graphene::net::detail::message_oriented_connection_impl::accept()::__lambda0>::run(void *, void *) (functor=0x7fffe01028d8, prom=0x7fffe01028d0)
    at /app/bts/graphene-test1.1/libraries/fc/include/fc/thread/task.hpp:83
#10 0x00000000025051b1 in fc::task_base::run_impl (this=0x7fffe01028e0)
    at /app/bts/graphene-test1.1/libraries/fc/src/thread/task.cpp:43
#11 0x0000000002505142 in fc::task_base::run (this=0x7fffe01028e0) at /app/bts/graphene-test1.1/libraries/fc/src/thread/task.cpp:32
#12 0x00000000024f9b62 in fc::thread_d::run_next_task (this=0x7fffe00008c0)
    at /app/bts/graphene-test1.1/libraries/fc/src/thread/thread_d.hpp:498
#13 0x00000000024fa006 in fc::thread_d::process_tasks (this=0x7fffe00008c0)
    at /app/bts/graphene-test1.1/libraries/fc/src/thread/thread_d.hpp:547
#14 0x00000000024f9679 in fc::thread_d::start_process_tasks (my=140736951486656)
    at /app/bts/graphene-test1.1/libraries/fc/src/thread/thread_d.hpp:475
#15 0x0000000002851541 in make_fcontext () at libs/context/src/asm/make_x86_64_sysv_elf_gas.S:64
#16 0x0000000000000000 in ?? ()
```

**Comment by abitmore** [comment]
Duplicate of #304
