### ISSUE TITLE
Witness received SIGABRT: Assertion `_closing_connections.find(peer_to_delete) == _closing_connections.end()' failed.

### ISSUE THREAD

**Issue by abitmore** [cryptonomex/graphene#304]
Running with commit a748883fed08a73afaec647e2e8827d07ca3c163

```
witness_node: /app/bts/graphene-test2b.3/libraries/net/node.cpp:1534: void graphene::net::detail::node_impl::schedule_peer_for_deletion(const peer_connection_ptr&): Assertion `_closing_connections.find(peer_to_delete) == _closing_connections.end()' failed.

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffff4d09700 (LWP 20433)]
0x00007ffff6c01cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:5656      ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.

(gdb) where
#0  0x00007ffff6c01cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff6c050d8 in __GI_abort () at abort.c:89
#2  0x00007ffff6bfab86 in __assert_fail_base (fmt=0x7ffff6d4b830 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n",
    assertion=assertion@entry=0x2b4ba08 "_closing_connections.find(peer_to_delete) == _closing_connections.end()",
    file=file@entry=0x2b4a930 "/app/bts/graphene-test2b.3/libraries/net/node.cpp", line=line@entry=1534,
    function=function@entry=0x2b532c0 <graphene::net::detail::node_impl::schedule_peer_for_deletion(std::shared_ptr<graphene::net::peer_connection> const&)::__PRETTY_FUNCTION__> "void graphene::net::detail::node_impl::schedule_peer_for_deletion(const peer_connection_ptr&)") at assert.c:92
#3  0x00007ffff6bfac32 in __GI___assert_fail (
    assertion=0x2b4ba08 "_closing_connections.find(peer_to_delete) == _closing_connections.end()",
    file=0x2b4a930 "/app/bts/graphene-test2b.3/libraries/net/node.cpp", line=1534,
    function=0x2b532c0 <graphene::net::detail::node_impl::schedule_peer_for_deletion(std::shared_ptr<graphene::net::peer_connection> const&)::__PRETTY_FUNCTION__> "void graphene::net::detail::node_impl::schedule_peer_for_deletion(const peer_connection_ptr&)")
    at assert.c:101
#4  0x00000000027add71 in graphene::net::detail::node_impl::schedule_peer_for_deletion (this=0xdfc3c70, peer_to_delete=...)
    at /app/bts/graphene-test2b.3/libraries/net/node.cpp:1534
#5  0x00000000027c372e in graphene::net::detail::node_impl::on_connection_closed (this=0xdfc3c70, originating_peer=0x7fffe01ce2a0)
    at /app/bts/graphene-test2b.3/libraries/net/node.cpp:2807
#6  0x00000000028a1c2c in graphene::net::peer_connection::on_connection_closed (this=0x7fffe01ce2a0,
    originating_connection=0x7fffe01ce2d0) at /app/bts/graphene-test2b.3/libraries/net/peer_connection.cpp:270
#7  0x00000000028aa34b in graphene::net::detail::message_oriented_connection_impl::read_loop (this=0x7fffe01689c0)
    at /app/bts/graphene-test2b.3/libraries/net/message_oriented_connection.cpp:217
#8  0x00000000028a9d43 in graphene::net::detail::message_oriented_connection_impl::__lambda1::operator() (__closure=0x7fffe00e3998)
    at /app/bts/graphene-test2b.3/libraries/net/message_oriented_connection.cpp:125
#9  0x00000000028aeef8 in fc::detail::void_functor_run<graphene::net::detail::message_oriented_connection_impl::connect_to(const fc::ip::endpoint&)::__lambda1>::run(void *, void *) (functor=0x7fffe00e3998, prom=0x7fffe00e3990)
    at /app/bts/graphene-test2b.3/libraries/fc/include/fc/thread/task.hpp:83
#10 0x00000000025d0a57 in fc::task_base::run_impl (this=0x7fffe00e39a0)
    at /app/bts/graphene-test2b.3/libraries/fc/src/thread/task.cpp:43
#11 0x00000000025d09e8 in fc::task_base::run (this=0x7fffe00e39a0) at /app/bts/graphene-test2b.3/libraries/fc/src/thread/task.cpp:32
#12 0x00000000025c5408 in fc::thread_d::run_next_task (this=0x7fffe00008c0)
    at /app/bts/graphene-test2b.3/libraries/fc/src/thread/thread_d.hpp:498
#13 0x00000000025c58ac in fc::thread_d::process_tasks (this=0x7fffe00008c0)
    at /app/bts/graphene-test2b.3/libraries/fc/src/thread/thread_d.hpp:547
#14 0x00000000025c4f1f in fc::thread_d::start_process_tasks (my=140736951486656)
    at /app/bts/graphene-test2b.3/libraries/fc/src/thread/thread_d.hpp:475
#15 0x000000000291f5f1 in make_fcontext () at libs/context/src/asm/make_x86_64_sysv_elf_gas.S:64
#16 0x0000000000000000 in ?? ()

(gdb) thread apply all bt

Thread 5 (Thread 0x7fffeffff700 (LWP 20434)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00000000026a3007 in boost::asio::detail::posix_event::wait<boost::asio::detail::scoped_lock<boost::asio::detail::posix_mutex> >
    (this=0x7ffff0003858, lock=...) at /app/boost_1_57_0.bin/include/boost/asio/detail/posix_event.hpp:106
#2  0x0000000002690f1d in boost::asio::detail::task_io_service::do_run_one (this=0x7ffff0003800, lock=..., this_thread=..., ec=...)
    at /app/boost_1_57_0.bin/include/boost/asio/detail/impl/task_io_service.ipp:380
#3  0x0000000002690b17 in boost::asio::detail::task_io_service::run (this=0x7ffff0003800, ec=...)
    at /app/boost_1_57_0.bin/include/boost/asio/detail/impl/task_io_service.ipp:149
#4  0x000000000269113f in boost::asio::io_service::run (this=0x7ffff0002c80)
    at /app/boost_1_57_0.bin/include/boost/asio/impl/io_service.ipp:59
#5  0x00000000026948a5 in boost::asio::detail::resolver_service_base::work_io_service_runner::operator() (this=0x7ffff0002d58)
    at /app/boost_1_57_0.bin/include/boost/asio/detail/impl/resolver_service_base.ipp:32
#6  0x00000000027591c4 in boost::asio::detail::posix_thread::func<boost::asio::detail::resolver_service_base::work_io_service_runner>::run (this=0x7ffff0002d50) at /app/boost_1_57_0.bin/include/boost/asio/detail/posix_thread.hpp:82
#7  0x0000000002694838 in boost::asio::detail::boost_asio_detail_posix_thread_function (arg=0x7ffff0002d50)
    at /app/boost_1_57_0.bin/include/boost/asio/detail/impl/posix_thread.ipp:64
#8  0x00007ffff7bc4182 in start_thread (arg=0x7fffeffff700) at pthread_create.c:312
#9  0x00007ffff6cc547d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 4 (Thread 0x7ffff4d09700 (LWP 20433)):
#0  0x00007ffff6c01cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff6c050d8 in __GI_abort () at abort.c:89
#2  0x00007ffff6bfab86 in __assert_fail_base (fmt=0x7ffff6d4b830 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n",
    assertion=assertion@entry=0x2b4ba08 "_closing_connections.find(peer_to_delete) == _closing_connections.end()",
    file=file@entry=0x2b4a930 "/app/bts/graphene-test2b.3/libraries/net/node.cpp", line=line@entry=1534,
    function=function@entry=0x2b532c0 <graphene::net::detail::node_impl::schedule_peer_for_deletion(std::shared_ptr<graphene::net::peer_connection> const&)::__PRETTY_FUNCTION__> "void graphene::net::detail::node_impl::schedule_peer_for_deletion(const peer_connection_ptr&)") at assert.c:92
#3  0x00007ffff6bfac32 in __GI___assert_fail (
    assertion=0x2b4ba08 "_closing_connections.find(peer_to_delete) == _closing_connections.end()",
    file=0x2b4a930 "/app/bts/graphene-test2b.3/libraries/net/node.cpp", line=1534,
    function=0x2b532c0 <graphene::net::detail::node_impl::schedule_peer_for_deletion(std::shared_ptr<graphene::net::peer_connection> const&)::__PRETTY_FUNCTION__> "void graphene::net::detail::node_impl::schedule_peer_for_deletion(const peer_connection_ptr&)")
    at assert.c:101
#4  0x00000000027add71 in graphene::net::detail::node_impl::schedule_peer_for_deletion (this=0xdfc3c70, peer_to_delete=...)
    at /app/bts/graphene-test2b.3/libraries/net/node.cpp:1534
#5  0x00000000027c372e in graphene::net::detail::node_impl::on_connection_closed (this=0xdfc3c70, originating_peer=0x7fffe01ce2a0)
    at /app/bts/graphene-test2b.3/libraries/net/node.cpp:2807
#6  0x00000000028a1c2c in graphene::net::peer_connection::on_connection_closed (this=0x7fffe01ce2a0,
    originating_connection=0x7fffe01ce2d0) at /app/bts/graphene-test2b.3/libraries/net/peer_connection.cpp:270
#7  0x00000000028aa34b in graphene::net::detail::message_oriented_connection_impl::read_loop (this=0x7fffe01689c0)
    at /app/bts/graphene-test2b.3/libraries/net/message_oriented_connection.cpp:217
#8  0x00000000028a9d43 in graphene::net::detail::message_oriented_connection_impl::__lambda1::operator() (__closure=0x7fffe00e3998)
    at /app/bts/graphene-test2b.3/libraries/net/message_oriented_connection.cpp:125
#9  0x00000000028aeef8 in fc::detail::void_functor_run<graphene::net::detail::message_oriented_connection_impl::connect_to(const fc::ip::endpoint&)::__lambda1>::run(void *, void *) (functor=0x7fffe00e3998, prom=0x7fffe00e3990)
    at /app/bts/graphene-test2b.3/libraries/fc/include/fc/thread/task.hpp:83
#10 0x00000000025d0a57 in fc::task_base::run_impl (this=0x7fffe00e39a0)
    at /app/bts/graphene-test2b.3/libraries/fc/src/thread/task.cpp:43
#11 0x00000000025d09e8 in fc::task_base::run (this=0x7fffe00e39a0) at /app/bts/graphene-test2b.3/libraries/fc/src/thread/task.cpp:32
#12 0x00000000025c5408 in fc::thread_d::run_next_task (this=0x7fffe00008c0)
    at /app/bts/graphene-test2b.3/libraries/fc/src/thread/thread_d.hpp:498
#13 0x00000000025c58ac in fc::thread_d::process_tasks (this=0x7fffe00008c0)
    at /app/bts/graphene-test2b.3/libraries/fc/src/thread/thread_d.hpp:547
#14 0x00000000025c4f1f in fc::thread_d::start_process_tasks (my=140736951486656)
    at /app/bts/graphene-test2b.3/libraries/fc/src/thread/thread_d.hpp:475
#15 0x000000000291f5f1 in make_fcontext () at libs/context/src/asm/make_x86_64_sysv_elf_gas.S:64
#16 0x0000000000000000 in ?? ()

Thread 3 (Thread 0x7ffff550a700 (LWP 20432)):
#0  0x00007ffff6cc5b13 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
#1  0x0000000002690296 in boost::asio::detail::epoll_reactor::run (this=0xdfc3a30, block=true, ops=...)
    at /app/boost_1_57_0.bin/include/boost/asio/detail/impl/epoll_reactor.ipp:392
#2  0x0000000002690e58 in boost::asio::detail::task_io_service::do_run_one (this=0xdfc3640, lock=..., this_thread=..., ec=...)
    at /app/boost_1_57_0.bin/include/boost/asio/detail/impl/task_io_service.ipp:356
#3  0x0000000002690b17 in boost::asio::detail::task_io_service::run (this=0xdfc3640, ec=...)
    at /app/boost_1_57_0.bin/include/boost/asio/detail/impl/task_io_service.ipp:149
#4  0x000000000269113f in boost::asio::io_service::run (this=0xdfbf130)
    at /app/boost_1_57_0.bin/include/boost/asio/impl/io_service.ipp:59
#5  0x0000000002769598 in fc::asio::default_io_service_scope::default_io_service_scope()::{lambda()#1}::operator()() const ()
    at /app/bts/graphene-test2b.3/libraries/fc/src/asio.cpp:105
#6  0x000000000277102a in boost::detail::thread_data<fc::asio::default_io_service_scope::default_io_service_scope()::{lambda()#1}>::run() (this=0xdfc3720) at /app/boost_1_57_0.bin/include/boost/thread/detail/thread.hpp:116
#7  0x00000000028e4b15 in boost::(anonymous namespace)::thread_proxy (param=0xdfc3720) at libs/thread/src/pthread/thread.cpp:173
#8  0x00007ffff7bc4182 in start_thread (arg=0x7ffff550a700) at pthread_create.c:312
#9  0x00007ffff6cc547d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 2 (Thread 0x7ffff6096700 (LWP 20417)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
#1  0x00000000025c29c2 in boost::condition_variable::do_wait_until (this=0x7ffff00008d8, m=..., timeout=...)
    at /app/boost_1_57_0.bin/include/boost/thread/pthread/condition_variable.hpp:108
#2  0x00000000025c214b in boost::condition_variable::wait_until (this=0x7ffff00008d8, lk=..., tp=...)
    at /app/boost_1_57_0.bin/include/boost/thread/pthread/condition_variable_fwd.hpp:253
#3  0x00000000025c82c2 in boost::condition_variable::wait_until<boost::chrono::steady_clock, boost::chrono::duration<long, boost::ratio<1l, 1000000000l> > > (this=0x7ffff00008d8, lock=..., t=...)
    at /app/boost_1_57_0.bin/include/boost/thread/pthread/condition_variable_fwd.hpp:181
#4  0x00000000025c5a82 in fc::thread_d::process_tasks (this=0x7ffff00008c0)
    at /app/bts/graphene-test2b.3/libraries/fc/src/thread/thread_d.hpp:598
#5  0x00000000025c4f1f in fc::thread_d::start_process_tasks (my=140737219922112)
    at /app/bts/graphene-test2b.3/libraries/fc/src/thread/thread_d.hpp:475
#6  0x000000000291f5f1 in make_fcontext () at libs/context/src/asm/make_x86_64_sysv_elf_gas.S:64
#7  0x0000000000000000 in ?? ()

Thread 1 (Thread 0x7ffff7fd8780 (LWP 19035)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
#1  0x00000000025c29c2 in boost::condition_variable::do_wait_until (this=0x32e1d68, m=..., timeout=...)
    at /app/boost_1_57_0.bin/include/boost/thread/pthread/condition_variable.hpp:108
#2  0x00000000025c214b in boost::condition_variable::wait_until (this=0x32e1d68, lk=..., tp=...)
    at /app/boost_1_57_0.bin/include/boost/thread/pthread/condition_variable_fwd.hpp:253
#3  0x00000000025c82c2 in boost::condition_variable::wait_until<boost::chrono::steady_clock, boost::chrono::duration<long, boost::ratio<1l, 1000000000l> > > (this=0x32e1d68, lock=..., t=...)
    at /app/boost_1_57_0.bin/include/boost/thread/pthread/condition_variable_fwd.hpp:181
#4  0x00000000025c5a82 in fc::thread_d::process_tasks (this=0x32e1d50)
    at /app/bts/graphene-test2b.3/libraries/fc/src/thread/thread_d.hpp:598
#5  0x00000000025c4f1f in fc::thread_d::start_process_tasks (my=53353808)
    at /app/bts/graphene-test2b.3/libraries/fc/src/thread/thread_d.hpp:475
#6  0x000000000291f5f1 in make_fcontext () at libs/context/src/asm/make_x86_64_sysv_elf_gas.S:64
Cannot access memory at address 0x7fffed50b000

```

**Comment by abitmore** [comment]
Logs: https://drive.google.com/open?id=0B3xrm70jSHn4UGh4eWE3X2VfYXc

**Comment by abitmore** [comment]
Happened again during the spam test.
commit a3082897aead754813ac524351b496cc8f14ce2d

**Comment by theoreticalbts** [comment]
Moving discussion to #428
