### ISSUE TITLE
Assertion `fork_history.back() == reference_point' failed - Crash

### ISSUE THREAD

**Issue by abitmore** [cryptonomex/graphene#314]
Commit f0f12076fa5d80e07758ae5104854efd1dcb748d

```
745500ms th_a       application.cpp:383           handle_block         ] Got block #199649 from network
745500ms th_a       db_block.cpp:98               push_block           ] new_block.block_num(): 199649 new_block.id(): 00030be11aae3a4891869a7ad9aab215e93aee36747089ms th_a       application.cpp:683           get_blockchain_synop ] synopsis: ["00030b6c048c2452ac552e476f913329d818074a","00030ba7eec13a91d97908a50549d874681ea35a","00030bc587cc15cfdf07f10a72804724cb51217d","00030bd4128e9547c6771b80e5ffff1fdeec37a4","00030bdba291f319d7f0f62ec67394ef613ca8a5","00030bdf303a78916851613360a845e22e0041d8","00030be11aae3a4891869a7ad9aab215e93aee36"]
749560ms th_a       application.cpp:683           get_blockchain_synop ] synopsis: ["00030b6c048c2452ac552e476f913329d818074a","00030ba7eec13a91d97908a50549d874681ea35a","00030bc587cc15cfdf07f10a72804724cb51217d","00030bd4128e9547c6771b80e5ffff1fdeec37a4","00030bdba291f319d7f0f62ec67394ef613ca8a5","00030bdf303a78916851613360a845e22e0041d8","00030be11aae3a4891869a7ad9aab215e93aee36"]
752624ms th_a       application.cpp:683           get_blockchain_synop ] synopsis: ["00030b6c048c2452ac552e476f913329d818074a","00030ba7eec13a91d97908a50549d874681ea35a","00030bc587cc15cfdf07f10a72804724cb51217d","00030bd4128e9547c6771b80e5ffff1fdeec37a4","00030bdba291f319d7f0f62ec67394ef613ca8a5","00030bdf303a78916851613360a845e22e0041d8","00030be11aae3a4891869a7ad9aab215e93aee36"]
752881ms th_a       application.cpp:683           get_blockchain_synop ] synopsis: ["00030b6c048c2452ac552e476f913329d818074a","00030ba7eec13a91d97908a50549d874681ea35a","00030bc587cc15cfdf07f10a72804724cb51217d","00030bd4128e9547c6771b80e5ffff1fdeec37a4","00030bdba291f319d7f0f62ec67394ef613ca8a5","00030bdf303a78916851613360a845e22e0041d8","00030be11aae3a4891869a7ad9aab215e93aee36"]
witness_node: /app/bts/graphene-test2b.7/libraries/app/application.cpp:624: virtual std::vector<fc::ripemd160> graphene::app::detail::application_impl::get_blockchain_synopsis(const item_hash_t&, uint32_t): Assertion `fork_history.back() == reference_point' failed.

Program received signal SIGABRT, Aborted.
0x00007ffff6c01cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56      ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.

(gdb) bt
#0  0x00007ffff6c01cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff6c050d8 in __GI_abort () at abort.c:89
#2  0x00007ffff6bfab86 in __assert_fail_base (fmt=0x7ffff6d4b830 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n",
    assertion=assertion@entry=0x2aa0530 "fork_history.back() == reference_point",
    file=file@entry=0x2a9fd58 "/app/bts/graphene-test2b.7/libraries/app/application.cpp", line=line@entry=624,
    function=function@entry=0x2aa5f00 <graphene::app::detail::application_impl::get_blockchain_synopsis(fc::ripemd160 const&, unsigned int)::__PRETTY_FUNCTION__> "virtual std::vector<fc::ripemd160> graphene::app::detail::application_impl::get_blockchain_synopsis(const item_hash_t&, uint32_t)") at assert.c:92
#3  0x00007ffff6bfac32 in __GI___assert_fail (assertion=0x2aa0530 "fork_history.back() == reference_point",
    file=0x2a9fd58 "/app/bts/graphene-test2b.7/libraries/app/application.cpp", line=624,
    function=0x2aa5f00 <graphene::app::detail::application_impl::get_blockchain_synopsis(fc::ripemd160 const&, unsigned int)::__PRETTY_FUNCTION__> "virtual std::vector<fc::ripemd160> graphene::app::detail::application_impl::get_blockchain_synopsis(const item_hash_t&, uint32_t)") at assert.c:101
#4  0x0000000001fd088e in graphene::app::detail::application_impl::get_blockchain_synopsis (this=0x3318140, reference_point=...,
    number_of_blocks_after_reference_point=0) at /app/bts/graphene-test2b.7/libraries/app/application.cpp:624
#5  0x000000000284d3a3 in graphene::net::detail::statistics_gathering_node_delegate_wrapper::__lambda59::operator() (
    __closure=0x7fffe411d868) at /app/bts/graphene-test2b.7/libraries/net/node.cpp:5296
#6  0x000000000285d444 in fc::detail::functor_run<graphene::net::detail::statistics_gathering_node_delegate_wrapper::get_blockchain_synopsis(const item_hash_t&, uint32_t)::__lambda59>::run(void *, void *) (functor=0x7fffe411d868, prom=0x7fffe411d950)
    at /app/bts/graphene-test2b.7/libraries/fc/include/fc/thread/task.hpp:77
#7  0x0000000002628a87 in fc::task_base::run_impl (this=0x7fffe411d888)
    at /app/bts/graphene-test2b.7/libraries/fc/src/thread/task.cpp:43
#8  0x0000000002628a18 in fc::task_base::run (this=0x7fffe411d888) at /app/bts/graphene-test2b.7/libraries/fc/src/thread/task.cpp:32
#9  0x000000000261d438 in fc::thread_d::run_next_task (this=0x334c040)
    at /app/bts/graphene-test2b.7/libraries/fc/src/thread/thread_d.hpp:498
#10 0x000000000261d8dc in fc::thread_d::process_tasks (this=0x334c040)
    at /app/bts/graphene-test2b.7/libraries/fc/src/thread/thread_d.hpp:547
#11 0x000000000261cf4f in fc::thread_d::start_process_tasks (my=53788736)
    at /app/bts/graphene-test2b.7/libraries/fc/src/thread/thread_d.hpp:475
#12 0x0000000002975b51 in make_fcontext () at libs/context/src/asm/make_x86_64_sysv_elf_gas.S:64
#13 0x0000000000000000 in ?? ()
```

**Comment by theoreticalbts** [comment]
Lots of logging for this now in f506c2b089c98c336eb0e8bf956131e556fea8ac, please post the last few lines of log here if the problem occurs again.

**Comment by abitmore** [comment]
Closing because it's too old.
