### ISSUE TITLE
assert( block_num != 0) fails when reindexing after upgrade

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#343]
It seems like a deterministic failure, will soon create a backtrace to figure out exactly what's happening.

**Comment by pch957** [comment]
```
(gdb) bt
#0  0x00007ffff6b88cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff6b8c0d8 in __GI_abort () at abort.c:89
#2  0x00007ffff6b81b86 in __assert_fail_base (fmt=0x7ffff6cd2830 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x2cf35f4 "block_num != 0",
    file=file@entry=0x2cf3518 "/home/alt/workspace/dac/graphene/libraries/chain/block_database.cpp", line=line@entry=128,
    function=function@entry=0x2cf4e00 <graphene::chain::block_database::fetch_block_id(unsigned int) const::__PRETTY_FUNCTION__> "graphene::chain::block_id_type graphene::chain::block_database::fetch_block_id(uint32_t) const") at assert.c:92
#3  0x00007ffff6b81c32 in __GI___assert_fail (assertion=0x2cf35f4 "block_num != 0",
    file=0x2cf3518 "/home/alt/workspace/dac/graphene/libraries/chain/block_database.cpp", line=128,
    function=0x2cf4e00 <graphene::chain::block_database::fetch_block_id(unsigned int) const::__PRETTY_FUNCTION__> "graphene::chain::block_id_type graphene::chain::block_database::fetch_block_id(uint32_t) const") at assert.c:101
#4  0x00000000026eeaa2 in graphene::chain::block_database::fetch_block_id (this=0x34fe120, block_num=0)
    at /home/alt/workspace/dac/graphene/libraries/chain/block_database.cpp:128
#5  0x00000000024356dd in graphene::chain::database::get_block_id_for_num (this=0x34fde60, block_num=0)
    at /home/alt/workspace/dac/graphene/libraries/chain/db_block.cpp:50
#6  0x00000000020b5798 in graphene::app::detail::application_impl::get_blockchain_synopsis (this=0x34fdd30, reference_point=...,
    number_of_blocks_after_reference_point=0) at /home/alt/workspace/dac/graphene/libraries/app/application.cpp:692
#7  0x00000000029754fb in graphene::net::detail::statistics_gathering_node_delegate_wrapper::<lambda()>::operator()(void) const (__closure=0x7fffdc0660a8)
    at /home/alt/workspace/dac/graphene/libraries/net/node.cpp:5394
#8  0x0000000002986118 in fc::detail::functor_run<graphene::net::detail::statistics_gathering_node_delegate_wrapper::get_blockchain_synopsis(const item_hash_t&, uint32_t)::<lambda()> >::run(void *, void *) (functor=0x7fffdc0660a8, prom=0x7fffdc066190) at /home/alt/workspace/dac/graphene/libraries/fc/include/fc/thread/task.hpp:77
#9  0x000000000274ae45 in fc::task_base::run_impl (this=0x7fffdc0660c8) at /home/alt/workspace/dac/graphene/libraries/fc/src/thread/task.cpp:43
#10 0x000000000274add6 in fc::task_base::run (this=0x7fffdc0660c8) at /home/alt/workspace/dac/graphene/libraries/fc/src/thread/task.cpp:32
#11 0x000000000273ec50 in fc::thread_d::run_next_task (this=0x3538ff0) at /home/alt/workspace/dac/graphene/libraries/fc/src/thread/thread_d.hpp:498
#12 0x000000000273f0f4 in fc::thread_d::process_tasks (this=0x3538ff0) at /home/alt/workspace/dac/graphene/libraries/fc/src/thread/thread_d.hpp:547
#13 0x000000000273e765 in fc::thread_d::start_process_tasks (my=55807984) at /home/alt/workspace/dac/graphene/libraries/fc/src/thread/thread_d.hpp:475
#14 0x0000000002aa7351 in make_fcontext ()
#15 0x0000000000000000 in ?? ()
```

**Comment by theoreticalbts** [comment]
We fixed this a long time ago.
