### ISSUE TITLE
Graphene Segfaulting on ArchLinux

### ISSUE THREAD

**Issue by xeroc** [cryptonomex/graphene#471]
We had an issue about this already some time ago but it still isn't fixed. So I
reopen the issue:

```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff4f7f700 (LWP 8485)]
0x0000000000f0fdf8 in websocketpp::processor::hybi13<fc::http::detail::asio_with_stub_log>::consume(unsigned char*, unsigned long, std::error_code&) ()
(gdb)
(gdb) backtrace
#0  0x0000000000f0fdf8 in websocketpp::processor::hybi13<fc::http::detail::asio_with_stub_log>::consume(unsigned char*, unsigned long, std::error_code&) ()
#1  0x0000000000ef1309 in websocketpp::connection<fc::http::detail::asio_with_stub_log>::handle_read_frame(std::error_code const&, unsigned long) ()
#2  0x0000000000ec2f84 in websocketpp::transport::asio::connection<fc::http::detail::asio_with_stub_log::transport_config>::handle_async_read(boost::system::error_code const&, unsigned long) ()
#3  0x0000000000ed9885 in boost::asio::detail::completion_handler<boost::asio::detail::binder2<std::_Bind<std::_Mem_fn<void (websocketpp::transport::asio::connection<fc::http::detail::asio_with_stub_log::transport_config>::*)(boost::system::error_code const&, unsigned long)> (std::shared_ptr<websocketpp::transport::asio::connection<fc::http::detail::asio_with_stub_log::transport_config> >, std::_Placeholder<1>, std::_Placeholder<2>)>, boost::system::error_code, unsigned long> >::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long) ()
#4  0x0000000000ed9af6 in void boost::asio::detail::strand_service::dispatch<boost::asio::detail::binder2<std::_Bind<std::_Mem_fn<void (websocketpp::transport::asio::connection<fc::http::detail::asio_with_stub_log::transport_config>::*)(boost::system::error_code const&, unsigned long)> (std::shared_ptr<websocketpp::transport::asio::connection<fc::http::detail::asio_with_stub_log::transport_config> >, std::_Placeholder<1>, std::_Placeholder<2>)>, boost::system::error_code, unsigned long> >(boost::asio::detail::strand_service::strand_impl*&, boost::asio::detail::binder2<std::_Bind<std::_Mem_fn<void (websocketpp::transport::asio::connection<fc::http::detail::asio_with_stub_log::transport_config>::*)(boost::system::error_code const&, unsigned long)> (std::shared_ptr<websocketpp::transport::asio::connection<fc::http::detail::asio_with_stub_log::transport_config> >, std::_Placeholder<1>, std::_Placeholder<2>)>, boost::system::error_code, unsigned long>&) ()
#5  0x0000000000ed9c21 in std::_Function_handler<void (boost::system::error_code const&, unsigned long), boost::asio::detail::wrapped_handler<boost::asio::io_service::strand, std::_Bind<std::_Mem_fn<void (websocketpp::transport::asio::connection<fc::http::detail::asio_with_stub_log::transport_config>::*)(boost::system::error_code const&, unsigned long)> (std::shared_ptr<websocketpp::transport::asio::connection<fc::http::detail::asio_with_stub_log::transport_config> >, std::_Placeholder<1>, std::_Placeholder<2>)>, boost::asio::detail::is_continuation_if_running> >::_M_invoke(std::_Any_data const&, boost::system::error_code const&, unsigned long&&) ()
#6  0x0000000000edaeed in boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >, boost::asio::mutable_buffers_1, boost::asio::detail::transfer_at_least_t, websocketpp::transport::asio::custom_alloc_handler<std::function<void (boost::system::error_code const&, unsigned long)> > >::operator()(boost::system::error_code const&, unsigned long, int) ()
#7  0x0000000000edb4ad in boost::asio::detail::reactive_socket_recv_op<boost::asio::mutable_buffers_1, boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >, boost::asio::mutable_buffers_1, boost::asio::detail::transfer_at_least_t, websocketpp::transport::asio::custom_alloc_handler<std::function<void (boost::system::error_code const&, unsigned long)> > > >::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long) ()
#8  0x0000000000e63b75 in boost::asio::detail::epoll_reactor::descriptor_state::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long) ()
#9  0x0000000000f1f356 in fc::asio::default_io_service_scope::default_io_service_scope()::{lambda()#1}::operator()() const ()
#10 0x000000000106d395 in thread_proxy ()
#11 0x00007ffff774a4a4 in start_thread () from /usr/lib/libpthread.so.0
#12 0x00007ffff5e4213d in clone () from /usr/lib/libc.so.6
```

**Comment by xeroc** [comment]
dublicate #365
