### ISSUE TITLE
witness_node frozen: ntp.cpp exception - unspecified process exited with: Too many open files

### ISSUE THREAD

**Issue by roadscape** [cryptonomex/graphene#486]
Running 2.0.151216b

Witness node was missing blocks.. output:

```
1188244ms th_a       application.cpp:496           handle_block         ] Got block: #1856270 time: 2015-12-17T11:19:48 latency: 245 ms from: wackou  irreversible: 1856252 (-18)
1190119ms th_a       application.cpp:816           get_blockchain_synop ] synopsis: ["001c52fa167aa457c8d19f1fe054da17b8bd4f16","001c5305fc5b557cde4a358d2f59c65f1b3e377b","001c530a0d877a4e86554d1518be7958687b43fe","001c530da67640674387db82d7d828b8b7772ce0","001c530ea708aa6e8a1110336ffa81f99c8a3856"]
1191126ms th_a       application.cpp:496           handle_block         ] Got block: #1856271 time: 2015-12-17T11:19:51 latency: 127 ms from: delegate-clayop  irreversible: 1856253 (-18)
3403314ms ntp        ntp.cpp:98                    request_now          ] 0 exception: unspecified
process exited with: Too many open files
    {"message":"Too many open files"}
    asio  asio.cpp:88 resolve_handler

    {}
    ntp  asio.cpp:160 resolve
103382ms ntp        ntp.cpp:177                   read_loop            ] ntp_delta_time updated to 1504 us
103625ms ntp        ntp.cpp:177                   read_loop            ] ntp_delta_time updated to 700 us
403839ms ntp        ntp.cpp:177                   read_loop            ] ntp_delta_time updated to 3911 us
^[[A^C
Program received signal SIGINT, Interrupt.
0x0000000000e13430 in void fc::divide<fc::uint128>(fc::uint128 const&, fc::uint128 const&, fc::uint128&, fc::uint128&) ()
(gdb) signal SIGINT
Continuing with signal SIGINT.
420707ms asio       main.cpp:167                  operator()           ] Caught SIGINT attempting to exit cleanly
^C
Program received signal SIGINT, Interrupt.
0x0000000000c72468 in graphene::chain::asset_bitasset_data_object::asset_bitasset_data_object(graphene::chain::asset_bitasset_data_object const&) ()
(gdb) bt
#0  0x0000000000c72468 in graphene::chain::asset_bitasset_data_object::asset_bitasset_data_object(graphene::chain::asset_bitasset_data_object const&) ()
#1  0x0000000000c2ac68 in graphene::chain::database::clear_expired_orders() ()
#2  0x0000000000c35deb in graphene::chain::database::_apply_block(graphene::chain::signed_block const&) ()
#3  0x0000000000c36bb5 in graphene::chain::database::apply_block(graphene::chain::signed_block const&, unsigned int) ()
#4  0x0000000000c37070 in graphene::chain::database::_push_block(graphene::chain::signed_block const&) ()
#5  0x0000000000c38c74 in graphene::chain::database::push_block(graphene::chain::signed_block const&, unsigned int) ()
#6  0x0000000000a87def in graphene::app::detail::application_impl::handle_block(graphene::net::block_message const&, bool, std::vector<fc::ripemd160, std::allocator<fc::ripemd160> >&) ()
#7  0x0000000000f77417 in fc::detail::functor_run<graphene::net::detail::statistics_gathering_node_delegate_wrapper::handle_block(graphene::net::block_message const&, bool, std::vector<fc::ripemd160, std::allocator<fc::ripemd160> >&)::{lambda()#1}>::run(void*, fc::detail::functor_run<graphene::net::detail::statistics_gathering_node_delegate_wrapper::handle_block(graphene::net::block_message const&, bool, std::vector<fc::ripemd160, std::allocator<fc::ripemd160> >&)::{lambda()#1}>) ()
#8  0x0000000000e320f3 in fc::task_base::run_impl() ()
#9  0x0000000000e3025e in fc::thread_d::process_tasks() ()
#10 0x0000000000e304d1 in fc::thread_d::start_process_tasks(long) ()
#11 0x0000000001098041 in make_fcontext ()
#12 0x0000000000000000 in ?? ()
```

**Comment by theoreticalbts** [comment]
Looks like #485 is the problem.  The "Too many open files" error may be informative

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#140
