### ISSUE TITLE
Market history crash

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#602]
@valzav reports the following crash:

```
#0  0x0000000000c0f723 in void boost::multi_index::detail::hashed_index_node_alg<boost::multi_index::detail::hashed_index_node_impl<std::allocator<char> >, boost::multi_index::detail::hashed_unique_tag>::unlink<boost::multi_index::detail::default_assigner>(boost::multi_index::detail::hashed_index_node_impl<std::allocator<char> >*, boost::multi_index::detail::default_assigner&) ()
#1  0x0000000000c16b6d in boost::multi_index::detail::hashed_index<boost::multi_index::member<graphene::db::object, graphene::db::object_id_type, &graphene::db::object::id>, boost::hash<graphene::db::object_id_type>, std::equal_to<graphene::db::object_id_type>, boost::multi_index::detail::nth_layer<1, graphene::market_history::order_history_object, boost::multi_index::indexed_by<boost::multi_index::hashed_unique<boost::multi_index::tag<graphene::chain::by_id, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, boost::multi_index::member<graphene::db::object, graphene::db::object_id_type, &graphene::db::object::id>, mpl_::na, mpl_::na>, boost::multi_index::ordered_unique<boost::multi_index::tag<graphene::market_history::by_key, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, boost::multi_index::member<graphene::market_history::order_history_object, graphene::market_history::history_key, &graphene::market_history::order_history_object::key>, mpl_::na>, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, std::allocator<graphene::market_history::order_history_object> >, boost::mpl::v_item<graphene::chain::by_id, boost::mpl::vector0<mpl_::na>, 0>, boost::multi_index::detail::hashed_unique_tag>::modify_(boost::multi_index::detail::hashed_index_node<boost::multi_index::detail::ordered_index_node<boost::multi_index::detail::index_node_base<graphene::market_history::order_history_object, std::allocator<graphene::market_history::order_history_object> > >, boost::multi_index::detail::hashed_unique_tag>*) ()
#2  0x0000000000c16ce9 in graphene::chain::generic_index<graphene::market_history::order_history_object, boost::multi_index::multi_index_container<graphene::market_history::order_history_object, boost::multi_index::indexed_by<boost::multi_index::hashed_unique<boost::multi_index::tag<graphene::chain::by_id, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, boost::multi_index::member<graphene::db::object, graphene::db::object_id_type, &graphene::db::object::id>, mpl_::na, mpl_::na>, boost::multi_index::ordered_unique<boost::multi_index::tag<graphene::market_history::by_key, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, boost::multi_index::member<graphene::market_history::order_history_object, graphene::market_history::history_key, &graphene::market_history::order_history_object::key>, mpl_::na>, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, std::allocator<graphene::market_history::order_history_object> > >::modify(graphene::db::object const&, std::function<void (graphene::db::object&)> const&) ()
#3  0x0000000000c16f4e in graphene::db::primary_index<graphene::chain::generic_index<graphene::market_history::order_history_object, boost::multi_index::multi_index_container<graphene::market_history::order_history_object, boost::multi_index::indexed_by<boost::multi_index::hashed_unique<boost::multi_index::tag<graphene::chain::by_id, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, boost::multi_index::member<graphene::db::object, graphene::db::object_id_type, &graphene::db::object::id>, mpl_::na, mpl_::na>, boost::multi_index::ordered_unique<boost::multi_index::tag<graphene::market_history::by_key, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, boost::multi_index::member<graphene::market_history::order_history_object, graphene::market_history::history_key, &graphene::market_history::order_history_object::key>, mpl_::na>, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na>, std::allocator<graphene::market_history::order_history_object> > > >::modify(graphene::db::object const&, std::function<void (graphene::db::object&)> const&) ()
#4  0x0000000000c5a45e in graphene::chain::database::perform_chain_maintenance(graphene::chain::signed_block const&, graphene::chain::global_property_object const&) ()
#5  0x0000000000c62a91 in graphene::chain::database::_apply_block(graphene::chain::signed_block const&) ()
#6  0x0000000000c63542 in graphene::chain::database::apply_block(graphene::chain::signed_block const&, unsigned int) ()
#7  0x0000000000c63a02 in graphene::chain::database::_push_block(graphene::chain::signed_block const&) ()
#8  0x0000000000c65743 in graphene::chain::database::push_block(graphene::chain::signed_block const&, unsigned int) ()
#9  0x0000000000a95266 in graphene::app::detail::application_impl::handle_block(graphene::net::block_message const&, bool, std::vector<fc::ripemd160, std::allocator<fc::ripemd160> >&) ()
#10 0x0000000000fad057 in fc::detail::functor_run<graphene::net::detail::statistics_gathering_node_delegate_wrapper::handle_block(graphene::net::block_message const&, bool, std::vector<fc::ripemd160, std::allocator<fc::ripemd160> >&)::{lambda()#1}>::run(void*, fc::detail::functor_run<graphene::net::detail::statistics_gathering_node_delegate_wrapper::handle_block(graphene::net::block_message const&, bool, std::vector<fc::ripemd160, std::allocator<fc::ripemd160> >&)::{lambda()#1}>) ()
#11 0x0000000000e5faa5 in fc::task_base::run_impl() ()
#12 0x0000000000e5d69f in fc::thread_d::process_tasks() ()
#13 0x0000000000e5d901 in fc::thread_d::start_process_tasks(long) ()
#14 0x00000000010d3d21 in make_fcontext ()
```

This does not happen on reindex.

A `hashed_unique` index needs to be replaced with `ordered_unique` in `market_history_plugin.hpp`, it might fix the problem.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#185
